name: workflow_lula
on:
    issues:
        types: [open]
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: action/luisagnol/teste_deploy/.github/workflows/secundario_wkf.yml@main
      with:
        repo-token: ${{ secrets.envPAT }}
        configuration-path: ${{ inputs.config-path }}
